# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0neBm2yDBzBcIYlTu0AtBzexxlyFWw6
"""

from google.colab import files
a=files.upload()

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics

data=pd.read_csv("housing.csv")
data.head(5)

data.isnull().sum()

x=data.iloc[:,0:3].values
y=data.iloc[:,3].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

reg=DecisionTreeRegressor(random_state=0)
reg.fit(x_train,y_train)

print("accuracy score=",metrics.accuracy_score(y_test,reg.predict(x_test)))

